import {
  FaLaptop,
  FaMobileAlt,
  FaMotorcycle,
  FaTshirt,
  FaShoppingBag,
  FaGem,
  FaCouch,
  FaAppleAlt,
  FaHome,
  FaUtensils,
  FaRunning,
  FaGlasses,
  FaCar,
  FaClock,
} from "react-icons/fa";

import { GiPerfumeBottle, GiLipstick } from "react-icons/gi";

export const categoryIcons = {
  beauty: <GiLipstick />,
  fragrances: <GiPerfumeBottle />,
  furniture: <FaCouch />,
  groceries: <FaAppleAlt />,
  "home-decoration": <FaHome />,
  "kitchen-accessories": <FaUtensils />,
  laptops: <FaLaptop />,
  "mens-shirts": <FaTshirt />,
  "mens-shoes": <FaTshirt />,
  "mens-watches": <FaClock />,
  "mobile-accessories": <FaMobileAlt />,
  motorcycle: <FaMotorcycle />,
  "skin-care": <GiLipstick />,
  smartphones: <FaMobileAlt />,
  "sports-accessories": <FaRunning />,
  sunglasses: <FaGlasses />,
  tablets: <FaMobileAlt />,
  tops: <FaTshirt />,
  vehicle: <FaCar />,
  "womens-bags": <FaShoppingBag />,
  "womens-dresses": <FaTshirt />,
  "womens-jewellery": <FaGem />,
  "womens-shoes": <FaTshirt />,
  "womens-watches": <FaClock />,
};
